### ISSUE TITLE
Could not pass event EntityDamageByEntityEvent to PvPManager v2.4.6

### ISSUE THREAD

**Issue by SmallSansSerif** [NoChanceSD/PvPManager#10]
Getting this error lately with latest builds of Spigot 1.8. http://pastebin.com/767hRcqn

[11:19:31] [Server thread/ERROR]: Could not pass event EntityDamageByEntityEvent to PvPManager v2.4.6 

Caused by: java.lang.ClassCastException: org.bukkit.craftbukkit.v1_8_R1.projectiles.CraftBlockProjectileSource cannot be cast to org.bukkit.entity.Entity

**Comment by NoChanceSD** [comment]
I guess Spigot changed something about ProjectileSource, i will have to update a fix for that.

**Comment by SmallSansSerif** [comment]
Ok thanks. I'll keep an eye out for a fixed build.

**Comment by NoChanceSD** [comment]
Does it happen when shooting a bow? I don't get the error, it's with a projectile of some sort i guess.

**Comment by SmallSansSerif** [comment]
Hmm. Don't know I have just been seeing it in the log lately.

**Comment by NoChanceSD** [comment]
Ok, i was releasing an update now but won't fix that, i can't get the error here.

**Comment by SmallSansSerif** [comment]
Could it maybe be one of the new 1.8 mob projectiles like the Guardian?

**Comment by NoChanceSD** [comment]
No, i found it, it's when filling a dispenser with arrows and firing to a player.
Something that does not happen very often xD

**Comment by SmallSansSerif** [comment]
Lol, awesome. Glad you found it.
