### ISSUE TITLE
PVP enable/disable

### ISSUE THREAD

**Issue by Shippy2208** [NoChanceSD/PvPManager#101]
I am having an issue when trying to enable pvp and disable in certain worlds.

The default pvp setting is set to true and I have added my spawn world into the exclusions list and when a player joins the server, pvp is disabled and when they join another world it gets enabled (which is what I want) but then when they go from that world back to the spawn, pvp doesn't get disabled.

I have tried adding the permissions "pvpmanager.nopvp" to the spawn world but this still doesn't work.

_Note: I don't want players to have access to the /pvp command._

Is this a bug with the plugin or have I done something wrong?

**Comment by NoChanceSD** [comment]
Can you show me your config file and your version? (use /ver pvpmanager)

**Comment by Shippy2208** [comment]
Sure, here is my config: http://pastebin.com/qTKmE2m3

The version is 3.0-SNAPSHOT-b196

**Comment by NoChanceSD** [comment]
So, any player in your server should have pvp on when he enters. Also when changing world it will force pvp to on if player has it disabled. That's how it should be working.
To disable pvp in one world maybe you should use worldguard global region.

**Comment by Shippy2208** [comment]
No, when players join the server (in the spawn world), their nametag goes red and /pvpstatus says their PvP is disabled (which is what should happen), then if they go to the other world they get a message saying PvP enabled, their name tag goes green and /pvpstatus says pvp enabled (which should also happen). But when they go from the other world then back to the spawn, their name tag doesn't go green it stays red and /pvp status says pvp enabled and I don't want this to happen.

**Comment by EvilOlaf** [comment]
You could add the spawnworld, where you want to have pvp disabled at all except from the worlds PvPManager is active and disable pvp there by gamerule, WorldGuard, whatever.

**Comment by Shippy2208** [comment]
But that won't change the nametag colours... Which is what I want.

**Comment by NoChanceSD** [comment]
You have "Default PvP: true" so your players should start with pvp enabled. If they don't, then i guess it's a bug on the plugin.

**Comment by Shippy2208** [comment]
Yes, default pvp is set to true.

**Comment by NoChanceSD** [comment]
Maybe you could use some plugin that executes commands when players change world. Then you could disable or enable PvP easily.

**Comment by CloudeLecaw** [comment]
have you ever yt tried a plugin liem RedProtect? it works in hook with PvPManager and has a ForcePvP flag. is u use it on a global worldflag (all world where PvP is Forced to be on - thenand the player enter the world their PVP got forced on (also the tags) if they leave to a region/wolrd where forcedPVP flag is false then the PVPState goes disabled...

this region plugin works together with PVPManager like u wished it..
PVP-Manager default: PvP-Disabled
Region on Spawn ForcePvp: false  - all other WorldsPvPForce: True
Reult:
PVP is enabled (also in TAB) in all worlds. only on the Spwnworld its disbaled

Tada...thats what u wanted right?...

**Comment by NoChanceSD** [comment]
Closing as it doesn't seem an issue anymore.
