### ISSUE TITLE
Toggle doesn't seem to work?

### ISSUE THREAD

**Issue by Cassolotl** [NoChanceSD/PvPManager#104]
Hello,

I have the latest release installed, I think. 1.9, out on 21st March 2016. And whenever anyone tries to toggle PvP on or off, we get this message:

> Usage: /pvp [on|off] or /pvp [player] [on|off]

We're running Spigot 1.9.

**Comment by NoChanceSD** [comment]
Can you tell me the exact command you are trying to use?
Also, latest build if you want it http://ci.md-5.net/job/PvPManager/lastSuccessfulBuild/
It probably won't resolve this issue but just an fyi.

**Comment by Cassolotl** [comment]
@NoChanceSD I tried:

/pvp on
/pvp off
/pvp Cassolotl on
/pvp Cassolotl off

Same result for all, and other players tested it at the same time and reported the same thing.

**Comment by NoChanceSD** [comment]
I just tried with latest build and had no issues.

**Comment by Cassolotl** [comment]
Okay - I'll uninstall and reinstall, check permissions etc.
