### ISSUE TITLE
amour bar error!

### ISSUE THREAD

**Issue by tuanjr** [NoChanceSD/PvPManager#105]
i have a latest version of pvpmanager download from here: http://ci.md-5.net/job/PvPManager/
and i found a bug with feature "kill when player combat logout". 
as you can see in this video: https://vimeo.com/164833537
(my network has error, so i cant upload to youtube)

**Comment by NoChanceSD** [comment]
This is only on premium version right?

**Comment by tuanjr** [comment]
both free version and premium,

**Comment by NoChanceSD** [comment]
So, like i said in the discussion thread. Not sure if this is a minecraft or spigot bug yet, i verified it does happen with other pvp log plugins though.
To make it happen it simply takes killing a player right before he logs out.

**Comment by NoChanceSD** [comment]
I think minecraft or spigot fixed this bug, doesn't happen anymore to me.
