### ISSUE TITLE
build 228 broken

### ISSUE THREAD

**Issue by seema84** [NoChanceSD/PvPManager#110]
in the latest build 228 the main command /pvp on or /pvp name on dont work
i get every time only the usage message ...

**Comment by NoChanceSD** [comment]
Are you OP or got permission to use it?

**Comment by EvilOlaf** [comment]
Not reproducable for me.

**Comment by seema84** [comment]
i have try it with both

**Comment by seema84** [comment]
ok with new configs it works ... you can close this issue

**Comment by seema84** [comment]
I found the problem - all commands dont work with other Locals as "en"

**Comment by seema84** [comment]
close without comment? nice
