### ISSUE TITLE
Push back causing player kicks

### ISSUE THREAD

**Issue by EvilOlaf** [NoChanceSD/PvPManager#115]
Since I updated PM to a version with push back from regions integrated I receive player getting kicked for flying.

```
[17:52:33] [Server thread/WARN]: xxx was kicked for floating too long!
[17:52:33] [Server thread/INFO]: xxx lost connection: Flying is not enabled on this server
```

Spigot 1.8.8
PM 3.1.8

**Comment by NoChanceSD** [comment]
Are you sure it was the push back causing that? And are you using NoCheatPlus or any anti hack?

**Comment by EvilOlaf** [comment]
This started happening since I upgraded to a build containing the push back feature, so I am partially sure that PM causing this. Disabled it for now.
NCP 3.14.0-SNAPSHOT-sMD5NET-b989

**Comment by NoChanceSD** [comment]
Still a problem?

**Comment by EvilOlaf** [comment]
Not sure. Have to check back later. Stay tuned.

**Comment by EvilOlaf** [comment]
Well I do not get any response on this so I assume this is fixed.
