### ISSUE TITLE
pvp region

### ISSUE THREAD

**Issue by seema84** [NoChanceSD/PvPManager#119]
senario:

one player has pvp disable
other player has pvp enable

in worldguard i set pvp allow in the global region

now can the "other" player attacke the first player while its a pvp region
but i need to set pvp allow on the global region otherwise i need to set pvp flags on all region separate

maybe you cant add a list with regions for worldguard and the changed pvp status? i think this is the best solution

**Comment by NoChanceSD** [comment]
Sorry, won't add this.
