### ISSUE TITLE
Suggest: random drop, not all drop

### ISSUE THREAD

**Issue by tuanjr** [NoChanceSD/PvPManager#120]
Can you add feature like this:
when player  logout in combat, instead of drop all player's items, now we can config percent (%) of random items in inventory will drop and permissions, just like this:

> random-drop:
>     lord:
>       permissions: permissions.lord
>       percent-drop: 20
>     king
>       permissions: permissions.king
>       percent-drop: 10
>

**Comment by NoChanceSD** [comment]
Won't add this sorry.
