### ISSUE TITLE
Outdated de locale

### ISSUE THREAD

**Issue by Vinc0682** [NoChanceSD/PvPManager#121]
Can you please just add these two lines to the german locale?

PvPList_Nothing_Found = &6[&8PvP&6] &cKeine Einträge.
Error_Player_Not_Found = &6[&8PvP&6] &cSpieler nicht gefunden.

This makes PvPManager working again on all german servers, maybe you can add an auto-updater for the messages or show a message to the owner / admins / OPs...

**Comment by NoChanceSD** [comment]
Yes i will add that thank you. Also, updating missing messages should be fixed now.
