### ISSUE TITLE
flame bow can damage the player, on pvp is off

### ISSUE THREAD

**Issue by mat41997** [NoChanceSD/PvPManager#122]
s1
![s1](https://cloud.githubusercontent.com/assets/5884000/16299840/b5665978-393c-11e6-9e36-cfcaa38f2455.png)

s2
![s2](https://cloud.githubusercontent.com/assets/5884000/16299842/b89c32a2-393c-11e6-8725-7180e3b6705b.png)

s3
![s3](https://cloud.githubusercontent.com/assets/5884000/16299847/c112a196-393c-11e6-9bb1-b474a70eef1b.png)

timings
https://timings.aikar.co/v2/?id=03ee69236fba42b2b7c355c637ad8a97

**Comment by NoChanceSD** [comment]
Can you check if this is fixed in latest build?

**Comment by mat41997** [comment]
thx. its work : )
