### ISSUE TITLE
Default PvP not working

### ISSUE THREAD

**Issue by Nentify** [NoChanceSD/PvPManager#123]
`Default PvP: false` is set in the config, but when users join, they can be attacked. Using the `/pvp` command says PvP is disabled. v2.4.9 running Thermos for MC 1.7.10.

**Comment by NoChanceSD** [comment]
That's way out of date, update pvpmanager.

**Comment by Nentify** [comment]
Do the latest versions work on 1.7.10? I was getting some errors.
