### ISSUE TITLE
"Your PvP was enabled because you entered a PvP allowed region"

### ISSUE THREAD

**Issue by BlackBeltPanda** [NoChanceSD/PvPManager#125]
After updating to the latest dev build, #234, players are getting the error, "Your PvP was enabled because you entered a PvP allowed region", and their PvP is enabled, whenever they're attacked by another player. I don't see a config option for this, is there a way to turn it off?

**Comment by EvilOlaf** [comment]
This is a breaking change since the last version as PM does not overrule the WorldGuard `pvp` flag anymore.

**Comment by BlackBeltPanda** [comment]
There's no PvP flag set in the regions that this is occurring in.

**Comment by EvilOlaf** [comment]
What about your `__global__` region? Does it have the `pvp` flag set?

**Comment by BlackBeltPanda** [comment]
It's set in __global__, but removing the flag seems to result in players not being able to PvP anywhere. O.o

https://i.gyazo.com/4c9e5deb0032f164dd7b5cbc867f25fa.png

**Comment by EvilOlaf** [comment]
Then something other is interfering.
Make sure no other plugin preventing pvp and also check if `pvp` is set to `true` in your `server.properties`.

**Comment by BlackBeltPanda** [comment]
Thanks, I got it working.

**Comment by NoChanceSD** [comment]
Glad you got it working, there will most likely be a config option though.

**Comment by BlackBeltPanda** [comment]
Dang, my Skyblock plugin keeps setting the PvP flag to "allow" in `__Global__` unless I disable PvP in the Skyblock config, at which point it sets the PvP flag to "deny". I can't win. >.<
