### ISSUE TITLE
Duplicated skins and nicknames

### ISSUE THREAD

**Issue by Twonox** [NoChanceSD/PvPManager#128]
When a player disconnect during PvP, his Skin is duplicated in spawn and same thing for his nick.

> http://image.noelshack.com/fichiers/2016/32/1470653030-2016-08-08-12-42-57.png
> http://image.noelshack.com/fichiers/2016/32/1470653038-2016-08-07-12-44-29.png

I use the `latest dev build` and my server is `PaperSpigot 1.7`

**Comment by NoChanceSD** [comment]
You are using the premium version of PvPManager right?

**Comment by Twonox** [comment]
No

**Comment by Twonox** [comment]
I use this: http://ci.md-5.net/job/PvPManager/238/
But with officiel version there is same problem.

**Comment by NoChanceSD** [comment]
It doesn't happen if you remove PvPManager?

**Comment by Twonox** [comment]
Yes

**Comment by Twonox** [comment]
I've found the cause.
When:
```
Kill on Logout:
      Enabled: true
```
This problem happens.

But if:
```
Kill on Logout:
      Enabled: false
```
This problem doesn't happen.

**Comment by Twonox** [comment]
Only in 1.7.10 (not in 1.8.8)

**Comment by NoChanceSD** [comment]
Just disable kill on logout then, sorry won't fix this one.
