### ISSUE TITLE
Player can pass worldborder if Disable teleport on pvp

### ISSUE THREAD

**Issue by tuanjr** [NoChanceSD/PvPManager#130]
if disable teleport on pvp, when player player in pvp, they can pass worldborder.
I use:
- pvpmanager premium latest version
- Worlborder plugin latest version http://dev.bukkit.org/bukkit-plugins/worldborder/
- Paperclip (Paperspigot) 1.9.2

here are config:
```
Tagged In Combat:
  Enabled: true
  Any Damage: false
  Time: 20
  NameTag Prefix: ''
  Block:
    EnderPearls: true
    Teleport: true
    Place Blocks: false
    Commands:
      Enabled: true
      Whitelist: true
      Command List:
      - tag
      - r
      - reply
      - w
      - tell
      - whisper
      - msg
      - t
      - m
```

**Comment by NoChanceSD** [comment]
Yep, just use minecraft worldborder or allow teleport. I won't change this.
