### ISSUE TITLE
VanishNoPacket integration

### ISSUE THREAD

**Issue by EvilOlaf** [NoChanceSD/PvPManager#131]
To cut it short:
Flint'n'steel can be used to detect vanish players with pvp disabled.

Version 3.3, build 238

**Comment by NoChanceSD** [comment]
Players come with clever ways xD
Isn't that plugin really outdated? I think it should be easy to fix though.

**Comment by NoChanceSD** [comment]
Let me know if this fixes it please.

**Comment by EvilOlaf** [comment]
VNP had its last official update a while ago, yes. But there are a few forks that at least try to compile it against the newest CB/Spigot builds as well as some miner issues.
https://github.com/mbax/VanishNoPacket/network

I'll give it a try tomorrow.

**Comment by EvilOlaf** [comment]
Due to lack of reponse (from server staff) I assume this is fixed.
