### ISSUE TITLE
Kingdoms support

### ISSUE THREAD

**Issue by renzotom** [NoChanceSD/PvPManager#132]
https://www.spigotmc.org/resources/kingdoms-battle-for-land-might-and-glory-1-8-x-1-9-x-1-10.11833/
Can you add support for this plugin please? There is also free version or contact author, he probably help you. I mean support - border, warzone, safezone - like in faction plugin.

**Comment by NoChanceSD** [comment]
The only support needed would be when anti border hopping is enabled and players are vulnerable to everything. That means they can also be attacked by players on their own kingdom. 
Is the free version kinda the same? I don't have access to the premium jar.

**Comment by renzotom** [comment]
I am not sure, try contact author of this plugin, maybe he help you. But, on free page you have what is and what isn´t in free version.

**Comment by NoChanceSD** [comment]
Plugin seems to be discontinued.
