### ISSUE TITLE
PVP MANAGER CONFLICTS WITH WORLDGUARD REGIONS

### ISSUE THREAD

**Issue by RAZERMC** [NoChanceSD/PvPManager#14]
scenario i create a world guard region then flag it as pvp, the player outside that region can hit the player inside the region which should not be. tested on spigot 1.8.3. bug goes away when removing pvpmanager. Please add support to worldguard regions and its pvp flag. very much appreciated the work you have done here. more support! note region outside the pvp region is flagged pvp deny thanks

**Comment by NoChanceSD** [comment]
I will test this maybe today if i get some free time.

**Comment by Dimatert9** [comment]
#19

**Comment by RAZERMC** [comment]
testing this today hope its gone
