### ISSUE TITLE
Tagged users can't PVP in safezone

### ISSUE THREAD

**Issue by MusConito** [NoChanceSD/PvPManager#141]
Hey! First of all, very nice plugin and happy new year!
Now, I have the **Anti Border Hopping: Vulnerable** on true.

Tested with two users, noone opped nor admin.
Have **Massivecraft factions 2.8.17**, **WorldGuard 6.1.3 SNAPSHOT** and **PermissionsEx 1.23.4**.
I created a **PVP allowed** region --IN-- a **__GLOBAL__ with no PVP tag** at all.

When I hit somebody in PVP region we can kill each other.
But we can't PVP in safezone (even tagged).

If you need more information, let me know.
Thanks!

**Comment by Sollembum78** [comment]
Same problem, latest 1.11.2 spigot, with WG 6.1.3

**Comment by EvilOlaf** [comment]
Did you try to set `WorldGuard Overrides: true` ?

**Comment by Sollembum78** [comment]
I did.

**Comment by NoChanceSD** [comment]
No errors in console?

**Comment by Sollembum78** [comment]
No errors, combat mode works like always but if you run into safe zone attacker gets default message, that you can't fight here. Tested with no global flags and with glogal pvp allow, same result.

**Comment by NoChanceSD** [comment]
It isn't happening for me, inside green area pvp is set to deny, outside has no flag
[http://imgur.com/zM5YMs0](url)
I wasn't using Factions though, maybe that's what causes the issue.

**Comment by Sollembum78** [comment]
NoChanceSD what versions of plugins do you use? What WorldGuard, spigot?

**Comment by NoChanceSD** [comment]
PvPManager v3.3.3.2
WorldGuard version 6.1.3-SNAPSHOT;1687-26e5995
Actually i was using PaperSpigot, forgot about that. I'm going to try with Spigot now but the result shouldn't change.

**Comment by Sollembum78** [comment]
Ok, I've been using normal spigot and WG that is the most recent official release (not snapshot). But just to test I've downloaded exact version you have, and still no result, player is tagged but as soon as he enters 'pvp deny zone' he is not vulnerable, and I see default 'You can't pvp here' message. 

I have tried jumping between 'no regions > pvp deny region' and 'pvp allow region > pvp deny region', with pvp allow for '__global__' and without any flags.

My versions of everything:
[http://imgur.com/yYCV6A0](http://imgur.com/yYCV6A0)

My config:
http://pastebin.com/XNG5YaUS

**Comment by NoChanceSD** [comment]
So the only difference seems to be PermissionsEx, i used GroupManager.
Also, both players you used are not OP right?

**Comment by Sollembum78** [comment]
Ok, somehow I got it working now, maybe it was OP thing for one of testers, but I'm not sure. I'll test more and write what I got.

**Comment by Sollembum78** [comment]
I still have no idea why it didn't work at first and now it does, cause there were cases when I tested with both mortal players, but now it works, on spigot and paperspigot, with snapshot and latest release of WG. 

And I've discovered plugin that for some reason breaks this feature - SimpleClans. (That I know after several hours of testing with all 50 of needed plugins).

Anyways, happy to get this working, thanks for support :)

**Comment by NoChanceSD** [comment]
I tried with PermissionsEx too and it worked same as before.
The only explanation i see is that one of the players was OP since both players need to be tagged to hit each other inside a safe zone and an OP doesn't get tagged.

Anyway, i'm glad it's working for you now. 
Still need to test with Factions and SimpleClans then, Also would like to know if @MusConito still has this issue.

**Comment by MusConito** [comment]
Im still having the same issue.
But I cant tell you certainly why...

When two users FACTIONLESS are tagged, they cannot attack in safezone.
If one of them is inside a faction, then the plugins do it thing.

Note that if I remove the factions plugin, everything works perfectly.
But it's a pretty common plugin, so... everyone should have the same problem.

**Comment by NoChanceSD** [comment]
Thanks, i think i found the issue. Apparently 2 factionless players are a recruit to each other instead of neutral or something else. Doesn't make much sense to me but should fix that problem.

**Comment by NoChanceSD** [comment]
This was fixed a long time ago i think.
