### ISSUE TITLE
Default Skins after PvP

### ISSUE THREAD

**Issue by AlexBaber** [NoChanceSD/PvPManager#143]
Hello!

I've experienced a slight bug with the PvPManager plugin.

When players experience the PvP tag system, after the timer runs out where they are free to TP, logout, etc; the people involved in PvP see other people which they were fighting as Steve/Alex skins. 

Example of what I'm try to explain:
**Player 1** fights _Player 2_ and then the PvP ends, **Player 1** will see _Player 2_ as an Alex/Steve skin, and the same for _Player 2_. Then **Player 1** fight Player 3, PvP ends and the same situation happens. 

Only fix I've found is to relog after PvP and the skins fix, until another PvP fight has occurred.

Hope you find a fix, thanks in advance! 
Loving the plugin also.

**Comment by NoChanceSD** [comment]
That's weird, is your server in offline mode?
If yes, what do you use to have skins?
Also, do you use any disguise plugin?

**Comment by NoChanceSD** [comment]
Likely caused by another plugin, not enough info.
