### ISSUE TITLE
[bug] Players can stack items they shouldnt when PVP tagged

### ISSUE THREAD

**Issue by FrozenBeard** [NoChanceSD/PvPManager#150]
once a player is PVP tagged that are able to stack items.
Here is a video of it in action.
https://www.youtube.com/watch?v=00qQKXSZhcY

**Comment by NoChanceSD** [comment]
This was 2 years ago but informing anyway, PvPManager doesn't stop players from dropping items, it was probably griefprevention.

**Comment by FrozenBeard** [comment]
It was GP.
