### ISSUE TITLE
1.12 issues.

### ISSUE THREAD

**Issue by EndermanHosting** [NoChanceSD/PvPManager#151]
I installed PvP Manager for my 1.12 Kit PvP server and it does not work correctly.
For example when I am typing "/pvp on" it says: Usage: /pvp on:off.

Also players do not get tagged when they enter the PvP area and get tagged by another player.

If you could help me with that I would love it :D

Thank you,
Endy

**Comment by EvilOlaf** [comment]
Check your console for errors.
