### ISSUE TITLE
Doesn't work with World Gaurd regions

### ISSUE THREAD

**Issue by Pine2apple** [NoChanceSD/PvPManager#155]
I got a 1.8.8 PvP Server (and don't tell me to update to 1.12, its a competitive pvp server, for 1.7-1.8) and even though i have pvp disabled in the safe-zone region, this plugin overrides worldgaurd and allows players to hit eachother in those regions. I am using the latest version of the plugin, and my server is 1.8.8

**Comment by EvilOlaf** [comment]
AFAIR there is a config option to toggle worldguard override

**Comment by NoChanceSD** [comment]
This is a feature of the plugin which can be disabled.
