### ISSUE TITLE
FactionsUUID and PVPManager issue

### ISSUE THREAD

**Issue by Cri16228** [NoChanceSD/PvPManager#157]
Hi, I have a friend with Faction server and he uses your PvPManager (Premium Version).
He uses it with FactionsUUID and the problem is when 2 players (neutral) do pvp in a faction territory (claimed by one of the 2 players) and if the player that owns the territory hit the other player and after the second one hit the first one (that own the territory) for some reasons he don't take knockback.
We have tried without PvPManager and he takes knockback. Can you help us to solve this problem

**Comment by NoChanceSD** [comment]
This plugin doesn't really change any knockbacks.
