### ISSUE TITLE
Error on startup (WorldGuard)

### ISSUE THREAD

**Issue by dunaland1** [NoChanceSD/PvPManager#171]
The plugin won't start because of changes in modern world guard versions (NoSuchMethodError).

To reproduce use the following setup:
Paper: 1.14.4-207
WorldGuard: 7.0.1-rc2;556b638
PvPManager: Build #282

Pastebin: https://pastebin.com/NHJGPmyw

**Comment by NoChanceSD** [comment]
I'm aware, the latest builds are still not finished for 1.14.
For now it only works with the old WorldGuard 6.

**Comment by NoChanceSD** [comment]
Try build 283, it should just say WorldGuard support is disabled but still enable.

**Comment by NoChanceSD** [comment]
This should be fixed.
