### ISSUE TITLE
[LITE] Commands on PVP enable/disable not running

### ISSUE THREAD

**Issue by smellyonionman** [NoChanceSD/PvPManager#176]
**Describe the bug**
Commands with or without quotes will not run as they do in-game.  I've tested this with privileged and non-privileged commands and they produce no output.

**To Reproduce**
1. Add a command to line 147 and/or 148 of config.yml
2. Test commands in-game for expected behaviour
3. Toggle PVP several times
4. Check console

**Expected behavior**
I've tried this with a line of Denizen code which only runs its script when fired manually in chat; not working in PVP config.  I've also tried using 'cmi mail send %p hi' and don't receive the mail when toggling PVP.

**Plugin and Server version**
Version: 3.5.2
Paper 225 / MC 1.14.4

**Additional context**
I'll update this issue and close if it works with double-quotes or a different placeholder than indicated (%p), otherwise I'm out of ideas!  Thanks.

**Comment by NoChanceSD** [comment]
I tested this and it worked as expected. Keep in mind it executes as the console. Should look like this: 
![image](https://user-images.githubusercontent.com/5256215/68865136-3173ad80-06ea-11ea-8818-87c032b406b9.png)
Just adding that and doing a /pm reload should work, you might need to add '' if the commands have special characters.

**Comment by smellyonionman** [comment]
Oh, big thank you for testing and for the example!
I was using {} instead of [] just after the colon, I guess the plural keyname was a good hint though.
