### ISSUE TITLE
PvPManager causing lag (with timings report)

### ISSUE THREAD

**Issue by Gioboi** [NoChanceSD/PvPManager#18]
http://timings.aikar.co/?url=11614604

       0.04%	  53.91%	  0.13 s	    26.95 ms	 0.0	       0.0k	    PlayerListener::onPlayerLogout(PlayerQuitEvent)

PlayerQuitEvent is causing lag

**Comment by NoChanceSD** [comment]
I wouldn't say causing lag, in 301 seconds it used 0.187 and in average the PlayerQuitEvent took 27 ms which is nothing you could actually notice but i will see what i can do.

**Comment by Her-Craving** [comment]
It's a slight lag spike. I only noticed it because it was highlighted in red in the timings report. Thought maybe you could do something about it. Thanks :)

**Comment by EvilOlaf** [comment]
What about 316% ?
`0.39%	 316.79%	  2.22 s	   158.40 ms	 0.0	       0.0k	    PlayerListener::onPlayerLogout(PlayerQuitEvent)`

**Comment by NoChanceSD** [comment]
@EvilOlaf The only thing i can think of is that saving to file (which is done on playerquitevent) would make that happen. Just curious, is your server running on a SSD or regular disk?

**Comment by EvilOlaf** [comment]
Unfortunately normal hard drive. It is dedicated though.

**Comment by NoChanceSD** [comment]
Alright, i guess that helps explain this. I will make saving to file run async though.

**Comment by NoChanceSD** [comment]
@EvilOlaf Can you see if this helps? Also if you have pvpmanager set to apply fines on pvp log then your economy plugin could be slowing down this method.

**Comment by EvilOlaf** [comment]
Yeah I can do that.
I do not use economy with PM.

**Comment by NoChanceSD** [comment]
I assume this hasn't caused more issues?

**Comment by EvilOlaf** [comment]
Don't think so. Guess we're cool here.
