### ISSUE TITLE
Anti Border Hopping

### ISSUE THREAD

**Issue by 11ironman111** [NoChanceSD/PvPManager#182]
Hi! Anti Border Hopping feature doesn't work on my server, and I don't know why...

Errors: 0
Server version: Paper 1.14.4
Worldguard version: 7.0.1;f2118aa
PvPManager Lite version: 3.6

Please help me

**Comment by NoChanceSD** [comment]
Be more specific about how it doesn't work, does it not push back, etc.

**Comment by 11ironman111** [comment]
Yea, the push back doesn't work and the wall doesn't appear either...

**Comment by 11ironman111** [comment]
Can someone help me? please

**Comment by NoChanceSD** [comment]
The plugin doesn't have a wall, only pushback. Check if there are any errors when starting the plugin and if it says "WorldGuard Found" please.
