### ISSUE TITLE
Adding command on combat tag as player

### ISSUE THREAD

**Issue by milkmoron** [NoChanceSD/PvPManager#188]
**Is your feature request related to a problem? Please describe.**

Hi I'm trying to add command on tag as a player but I'm not sure how to do it. I can't figure out if it's supported or not if you could add the ability that would be great for plugins whose API you don't support.

**Describe the solution you'd like**

**Comment by NoChanceSD** [comment]
You can already do it like this:
>Commands On Tag:
>  '- me hello
>  '- spawn

That's just an example, ignore the ' symbol please, i only used because github wasn't showing the "-"

**Comment by NoChanceSD** [comment]
Forgot to mention it's only on the premium version though, let me know if there's anything else you need and i will reopen.
