### ISSUE TITLE
pvp in worldguard region

### ISSUE THREAD

**Issue by Dimatert9** [NoChanceSD/PvPManager#19]
Hi. I found bug.
I have pvp off, but with flag pvp allow other players can attact me. But i cant.

**Comment by Dimatert9** [comment]
https://www.youtube.com/watch?v=2m4l52HDwcg&feature=youtu.be

**Comment by Dimatert9** [comment]
@NoChanceSD Not fixed in latest commit.
use wg 6.0 latest dev version.

**Comment by Dimatert9** [comment]
What i found. If 2 players have pvp off thay can pvp in worldguard region with pvp allow. If one player have pvp on and other player pvp off they cant pvp.

**Comment by Dimatert9** [comment]
Player who have pvp enable can start PvP. Playes who have pvp disable not can start pvp.

**Comment by NoChanceSD** [comment]
It should be fixed in next build, if players are inside PvP allow region they can always attack each other.
But not if one of them is outside the region, now it should work that way. Let me know if not.

**Comment by Dimatert9** [comment]
Not fixed.

**Comment by Dimatert9** [comment]
When player start attack other player he can use commands in battle, other player not can.

**Comment by Dimatert9** [comment]
When you stay in region with pvp allow you can pvp with pvp disable. Can you make if one player have pvp disable he can pvp and other can attack him in region with pvp allow

**Comment by NoChanceSD** [comment]
That is how i wanted it, inside region with pvp allow they can attack even with pvp disabled. It overrides PvPManager.

**Comment by Dimatert9** [comment]
Can you add in config this fuction to not pvp in pvp allow region with pvp disable? In other version in regions with pvp allow playars not can pvp. And sorry for my bad english.

**Comment by NoChanceSD** [comment]
Well ok i guess but they could also fight back xD

**Comment by Dimatert9** [comment]
Thanks! It work!

**Comment by NoChanceSD** [comment]
Good to know =D
