### ISSUE TITLE
Error durante PvP

### ISSUE THREAD

**Issue by SweetFlameCaster** [NoChanceSD/PvPManager#194]
Al hacer pvp aparecen letras y signos extraños en el chat.
La Foto fue después de golpear al jugador y a el también le aparece
Intente borrar el plugin y ponerlo de 0 porque había cambiado algunas cosas en la config pero aun asi aparece lo mismo
![2020-04-02_11 48 38](https://user-images.githubusercontent.com/63059493/78263166-fd056000-74d7-11ea-8f3b-20a150d57bef.png)

**Comment by NoChanceSD** [comment]
Make sure you save the config with UTF-8 encoding, use notepad++ or something similar to edit the config.

**Comment by SweetFlameCaster** [comment]
Ahora si funciona gracias por la ayuda. Saludos
