### ISSUE TITLE
Percantage based money penalty on PvPLog

### ISSUE THREAD

**Issue by Supergameplayer** [NoChanceSD/PvPManager#199]
I am trying to set up a PvP and MobArena server using this plugin, but can't seem to find a way to do percentage based money penalties on a player who PvPLogs. Percentage based money operations works really well with kill rewards, so it would also be nice to have it with PvPLog penalties.

**Comment by NoChanceSD** [comment]
Well, i started adding it to the premium version when i saw your other ticket, it's already there now. I might add it to this version later though, will leave this open.
