### ISSUE TITLE
Godmode is not automatically disabled for CommandBook

### ISSUE THREAD

**Issue by Towelie** [NoChanceSD/PvPManager#21]
I am using CommandBook for /god and it is not automatically disabled in PvP

**Comment by Dimatert9** [comment]
essentials gamemode too

**Comment by NoChanceSD** [comment]
It only disables gamemode, fly, disguises and invisibility, i guess i could add godmode in a future version.

**Comment by Towelie** [comment]
Would really appreciate that :). I must've misread about godmode.
