### ISSUE TITLE
Run specific commands when player enters pvp.

### ISSUE THREAD

**Issue by EnderGamingFilms** [NoChanceSD/PvPManager#213]
Hi, do you think you can add a section for commands that run whenever a player enters pvp? It would be extremely helpful to be able to run just a list of commands whenever a player enters or leaves pvp.

**Comment by NoChanceSD** [comment]
This is already a feature on the premium version, I'm not sure If I will be adding it here. But it is a pretty simple thing, might just port it to this version.

**Comment by EnderGamingFilms** [comment]
I'm ok with buying the premium, love supporting devs 🙂
