### ISSUE TITLE
[Suggestion] Please add a way to toggle the blood effects clientside

### ISSUE THREAD

**Issue by Towelie** [NoChanceSD/PvPManager#22]
I for one like the blood effects and don't want to disable them but there have been a couple of players on my server saying that the "gore" was "too much" for them and that they are going to stop playing if i don't disable it xD
I kid you not.

**Comment by NoChanceSD** [comment]
lol Ok, this is the first time i hear that xD
I could allow a player to disable/enable blood only for himself but i'm not sure if it's worth the trouble honestly...

**Comment by Towelie** [comment]
I admit it's silly xD But it force me to disable blood effect for a few people that were grossed out (weirdly, by pixelated red particles)

**Comment by NoChanceSD** [comment]
I thought about this and i don't think it's worth adding, sorry.
