### ISSUE TITLE
Kill Abuse > Respawn Protection protects on all teleports not just after death respawns with CMI TP.

### ISSUE THREAD

**Issue by TomLewis** [NoChanceSD/PvPManager#226]
**Describe the bug**
First the question is, the Respawn Protection setting, is that suppose to only be for on death respawns, so after you are killed you get that protected timer? or is it suppose to be for all respawns no matter what it is, for example teleports.
I'm under the impression its designed for Respawns after death only as its under the Kill Abuse section.
Whats happening is I use CMI teleports, and this Respawn Protection setting is being added to everyone for every teleport they make.

**To Reproduce**
1. Install CMI and use their teleport system
2. Teleport somewhere and get someone to attack you
3. They will be protected but they will be tagged in PvP by PvPManager

**Expected behavior**
For the Respawn Protection to only work for respawning after death, not on all teleports.

**Plugin and Server version**
3.7.14 (Free)
Paper 1.12.2

**Comment by NoChanceSD** [comment]
The protection is only activated when a player respawns(PlayerRespawnEvent basically), do you see the respawn protection message by pvpmanager? If not, it's most likely not pvpmanager blocking damage.

**Comment by TomLewis** [comment]
Yeah you were right, I found it to be CMi adding teleport protection without feedback.
