### ISSUE TITLE
Duplication glitch with GriefPrevention Siege

### ISSUE THREAD

**Issue by TomLewis** [NoChanceSD/PvPManager#240]
**Describe the bug**
I upgraded from the lite version to the premium version, NPC was automatically turned on for some reason. 
When players are in a /siege somehow this lets them dupe their inventory. 
Here's a video https://drive.google.com/file/d/1p9_3i09XMwgxdrUF912_FMGkj7g8JTuM/view

**To Reproduce**
1. /siege a player
2. Player items are dropped from loser on siege
3. Their NPC still has all the items.
4. Duped items.

**Expected behavior**
Hook into GP and don't duplicate items.

**Plugin and Server version**
3.13.4
Paper 1.12.2
GriefPrevenention: 16.8 (For 1.12.2)

**Video**
https://drive.google.com/file/d/1p9_3i09XMwgxdrUF912_FMGkj7g8JTuM/view

**Comment by NoChanceSD** [comment]
This is with kill on logout disabled in GP correct?  
I didn't want my plugin to be very intrusive so I just added a warning on server start but I might have to force disable some GP settings. Their lack of feedback messages makes server owners think some features are coming from my plugin when it's GP doing something.  
If this is unrelated to kill on logout then I have to test it out, never used siege before tbh.

**Comment by NoChanceSD** [comment]
Alright, seems like siege kills the player on logout regardless of any config setting. 
I believe I solved the issue, will be uploading to spigot soon, let me know if it's fixed when you try it.
Also, please use this repository: https://github.com/NoChanceSD/PvPManager-Issues for future tickets if the issue is about the premium version.

**Comment by TomLewis** [comment]
Brilliant thanks, Yeah Siege specifically, I have all other settings disabled in GP like "PunishLogout" is set to false as I didn't want any conflicts. 

Now that is speedy fix! Thank you!
