### ISSUE TITLE
pvpmanager.nodisable doesn't seem to work properly

### ISSUE THREAD

**Issue by BadassOverlord** [NoChanceSD/PvPManager#25]
I've added the permission pvpmanager.nodisable through the plugin "bpermissions". If I attack someone, neither me nor they will have their flight disabled. If they attack me however, their flight and my flight will be disabled. Not sure if intended or bug. Thought I should report nonetheless. I'm also using pvpmanager.admin, pvpmanager.override, and pvpmanager.override for myself. The person i'm attacking has no permissions from PVPManager.

**Comment by NoChanceSD** [comment]
Thanks, people were complaining that only the attacker would get fly disabled so i disabled it for both players without considering their permissions but will change that.
