### ISSUE TITLE
posibility of exemption on using signs

### ISSUE THREAD

**Issue by Bluesw** [NoChanceSD/PvPManager#26]
hi i was wondering could you add a sign use exemption so players could be tagged and still use signs to escape even though they are still in combat for another 10 secs thanks for reading this

**Comment by NoChanceSD** [comment]
Alright i will block using signs too.

**Comment by NoChanceSD** [comment]
Wait but all forms of teleport are already blocked, are you using latest build?

**Comment by NoChanceSD** [comment]
Well i'm closing this since it doesn't seem valid.

**Comment by Bluesw** [comment]
anyway to reopen as i could not reply as i have been so busy i know teleports are blocked what players want is essential warp signs that would still work while still tagged as new players  wanna escape arena quickly even when tagged

**Comment by NoChanceSD** [comment]
So you wanted the to allow use of signs in combat, is that right?

**Comment by Bluesw** [comment]
yes please that would be great :)
