### ISSUE TITLE
Suggestion for pvpmanager.nodisable permission

### ISSUE THREAD

**Issue by BadassOverlord** [NoChanceSD/PvPManager#28]
Hey, It's me again lol. I have a suggestion for the pvpmanager.nodisable permission: It shouldn't disable commands for anyone who has this permission either while in PVP. Also, if someone attacks with this permission, fly/gamemode/commands/disguises should be disabled for the person being attacked, but not for the person who attacked. This is assuming the person who attacked has the permission "pvpmanager.nodisable" and the person being attacked doesn't have this permission. Thanks.

**Comment by NoChanceSD** [comment]
I think it's best if disabled for the attacker, so he can't abuse fly, etc

**Comment by BadassOverlord** [comment]
Yeah, but commands shouldn't be disabled for the attacker. Giving this permission to someone is just asking for them to abuse it lol. If the attacker shouldn't abuse it, they shouldn't have the permission, simple as that.
