### ISSUE TITLE
Killing with PvP mode off

### ISSUE THREAD

**Issue by ghost** [NoChanceSD/PvPManager#314]
**Describe the bug**
Players can kill other players who have PvP off using crossbows with fireworks

**To Reproduce**
1. Player One turns PvP on
2. Player Two turns PvP off
3. Player One shoots Player Two with a crossbow loaded with fireworks
4. Player Two dies

**Expected behavior**
Player Two should not die

**Plugin and Server version**
  [Sat 02:26:51 INFO ] PvPManager version 3.10.6
  [Sat 02:26:51 INFO ] Allows Administrators To Change Their PvP Mechanics.
  [Sat 02:26:51 INFO ] Website: https://www.spigotmc.org/resources/pvpmanager-lite.845/
  [Sat 02:26:51 INFO ] Author: ChanceSD
  [Sat 02:26:57 INFO ] Checking version, please wait...
  [Sat 02:26:58 INFO ] This server is running Paper version git-Paper-132 (MC: 1.19.2) (Implementing API version 1.19.2-R0.1-SNAPSHOT) (Git: a76998d)
You are 2 version(s) behind
Download the new version at: https://papermc.io/downloads
Previous version: git-Paper-131 (MC: 1.19.2)

**Screenshots**
*Do not have one yet but will add soon*

**Additional context**
N/A

**Comment by ChanceSD** [comment]
I tested this and the firework did not do any damage with PvP off, does it need to be a specific firework explosion?
