### ISSUE TITLE
Enhancement: PVP toggle cooldown in minutes and warmup

### ISSUE THREAD

**Issue by EvilOlaf** [NoChanceSD/PvPManager#33]
Actually I want my  players to change their PVP status every two hours only.
But it looks quite awful when players gets a message like that they have to wait for another "7032 seconds".
So I would like to see this in minutes if `Cooldown(seconds):` is changeable to `Cooldown(minutes):`.

It would also be nice to add a warmup for the PVP toggle command.
Following scenario: Player A has PVP enabled and Player B does not. This is also in the tablist visible for both due to colored name tags.
Player A accepts a teleport request from player B. Player B now suddenly changes his PVP status, Player A does not recognize that fast enough and gets killed.

With warmup:
Player B uses `/pvp`. A broadcasts announces this PVP status change request and player B needs to wait for example three seconds (could also be combined with a movement/damage listener).

**Comment by NoChanceSD** [comment]
I can probably adapt it for minutes too but the warmup not sure if it's worth it.

**Comment by EvilOlaf** [comment]
Well this is your decision ;)
Can also be realized by using a 3rd party plugin like MyCommand.
