### ISSUE TITLE
Enhancement: Combine PVP status with other command/permissions

### ISSUE THREAD

**Issue by EvilOlaf** [NoChanceSD/PvPManager#34]
I have a mixed PVP server.
My apprehension is that most players will disable their PVP for the most time so they cannot be attacked. This would make players that really like PVP make sad, because the have way less "targets".

Actually there is not further benefit from having PVP enabled.
I suggest to add an option to run individual commands or grant permissions at change_enable and change_disable.

These could be positive effects (or if you like negative on PVP disable to punish cowards :D) or perks of mcMMO or whatever.

**Comment by NoChanceSD** [comment]
I think you could use some plugin that executes several commands for one command, i think bukkit itself has that function.
Example: Someone executes /pvp off and that makes the server execute other command as well. I don't know any plugin doing this but i'm sure there must be one.

**Comment by EvilOlaf** [comment]
There are a few issues with this.
Firstly `/pvp` does not force the use of a parameter `on` or `off`. It just changes the current status to the other.
So I don't explicitly know if the player turns his status on or off so I can not choose which additional commands to run either with a plugin as you suggested like MyCommand or with the `commands.yml` of Bukkit itself.

 For example if a player uses `/pvp` again within the cooldown period it would execute the additional commands regardless if the status has changed successfully as there is also nothing like an exit (Unix exit code like 0 = command was successful, 1 and higher was not successful, checkable by `echo $?`) code which could be asked for.

**Comment by NoChanceSD** [comment]
You are correct, didn't think about not using arguments. I guess the only way would be for an external plugin to hook into PvPManager, i feel i'm adding to many things to the plugin and i'm trying not to add this =/

**Comment by EvilOlaf** [comment]
Well same story as last time: It is your choice what you want to add and what not ;)
Keeping it small and clear has benefits too.
Maybe you wanna create an addon or something like one day :)
