### ISSUE TITLE
Potion issues

### ISSUE THREAD

**Issue by EvilOlaf** [NoChanceSD/PvPManager#35]
Usually when using an invisibility potion the player gets invisible as well as the name tag above his head.
With name tags enabled this nametag is still visible which makes these potions useless.

Also when PVP is disabled for a player and he uses a potion of invisibility he is still slightly visible (like a ghost) instead of being completely hidden except the potion effects.

I am actually not sure if this is wanted or not. For me these are issues anyways ;)

Best regards
Olaf

**Comment by NoChanceSD** [comment]
Hi, no this is not wanted, sorry for the delay. Anyway, does the "ghost" like thing happens only in PvP disabled or also in combat?
Thank you for the report.

**Comment by NoChanceSD** [comment]
I believe it should be fixed now.

**Comment by EvilOlaf** [comment]
Yes, as written above only when PVP is disabled.
Thanks
