### ISSUE TITLE
Only killing them once on combatlog

### ISSUE THREAD

**Issue by piecrustyumyum** [NoChanceSD/PvPManager#36]
When somebody kills somebody once and that person logs out and takes the punishment, they dont get punished again until I reload the plugin. Could this be fixed please? This is a issue in my book.

**Comment by NoChanceSD** [comment]
Hi, can you tell me which build are you using?

**Comment by piecrustyumyum** [comment]
Im trying to get it right now, I cant get into my server cause the authentication servers are down.

**Comment by piecrustyumyum** [comment]
Im using v3.0-SNAPSHOT-b102

I can try using the latest version before we go any further if you want.

**Comment by NoChanceSD** [comment]
Yes, please use the latest build: http://ci.md-5.net/job/PvPManager/lastSuccessfulBuild/
I'm currently trying to test if i can replicate this as i couldn't find the cause yet.

**Comment by piecrustyumyum** [comment]
If you would like to help me replicate it you could come on my server I dont have anybody on atm to help and I cant do it alone lol its fine if you dont though.

**Comment by NoChanceSD** [comment]
Sure, leave the IP, i will go there. I can delete these messages later if you want.

**Comment by piecrustyumyum** [comment]
pgu.ddns.net
That should be it

**Comment by NoChanceSD** [comment]
Fixed
