### ISSUE TITLE
not disabling fly on combattagged

### ISSUE THREAD

**Issue by piecrustyumyum** [NoChanceSD/PvPManager#37]
Can you please fix this issue, it is not disabling a persons fly mode on combat tag.

**Comment by NoChanceSD** [comment]
Need a better description, which person, the attacker or defender?
And also if you have the admin permission it won't disable fly for you.

**Comment by piecrustyumyum** [comment]
Well it doesnt disable it for anybody, I had two normal people without any permissions and gave them fly, and they started hitting each other and it didnt disable fly for either of them.

**Comment by NoChanceSD** [comment]
Fixed
