### ISSUE TITLE
Truced/Allied Factions

### ISSUE THREAD

**Issue by TheExceed** [NoChanceSD/PvPManager#38]
Truced/Allied factions can still pvp each other even if friendly fire in factions configs between those are disabled. I would like to have this fixed.

**Comment by NoChanceSD** [comment]
Factions and PvPManager version?

**Comment by Shmeeb** [comment]
FactionsUUID build 270

**Comment by TheExceed** [comment]
http://prntscr.com/7mxdag <- pvp manager
http://prntscr.com/7mxdgm <- factions

**Comment by TheExceed** [comment]
Anything on this?

**Comment by Shmeeb** [comment]
@NoChanceSD Any ideas?

**Comment by NoChanceSD** [comment]
Did you try the latest PvPManager build?

**Comment by NoChanceSD** [comment]
So i tried this and couldn't attack an allied faction, we are talking about the /f ally command right?
I'm closing this but let me know if it still happens.

**Comment by TheExceed** [comment]
No truced factions. /f truce

**Comment by Shmeeb** [comment]
On my server, players are able to attack members of their own faction
