### ISSUE TITLE
How can we disable the Action Bar message now we have boss bar timer?

### ISSUE THREAD

**Issue by TomLewis** [NoChanceSD/PvPManager#384]
**Is your feature request related to a problem? Please describe.**
Trying to figure out how to disable the Action bar message now we have a boss bar timer, the boss bar is way cleaner than the Action bar message and the action bar conflicts with CooldownsX when using an end pearl (Visually) it does make the timer go to 15s when in combat which is brilliant by the way, this is working well! Just the visuals that I need to solve now!

**Describe the solution you'd like**
A toggle to turn off action bar messages and stick to the Bossbar. a simple `Enabled: true` under action bar.

**Comment by ChanceSD** [comment]
You can just set the action bar message to empty to disable it fully, like `Message: ''`
Although I will turn that into a Enabled option at some point for better clarity

**Comment by TomLewis** [comment]
Thanks, yeah consistency between sections! I did think of that but thought, its going to try and send an empty message to the actionbar.
