### ISSUE TITLE
[Feature Request] WorldBorder Support

### ISSUE THREAD

**Issue by MeMyselfMC** [NoChanceSD/PvPManager#40]
The WorldBorder plugin (http://dev.bukkit.org/bukkit-plugins/worldborder/) teleports you backwards a configurable distance if you reach a set invisible border. However, since PvPManager prevents teleportation during combat, if you get tagged you can go through the border. What are the chances you can add support for it?

Quote from the WorldBorder developer:
"For reference, WorldBorder uses 'TeleportCause.PLUGIN'."

**Comment by EvilOlaf** [comment]
+1 !

A workaround for now might be setting `Ignore Zones For Tagged: false`.

**Comment by MeMyselfMC** [comment]
Thanks @EvilOlaf

**Comment by NoChanceSD** [comment]
I will make the teleport blocking configurable. 
However, are you not using 1.8? The vanilla worldborder is also pretty good.

**Comment by MeMyselfMC** [comment]
@NoChanceSD Yeah, I'm using 1.8, however since it's a PvP server I am aiming to keep the FPS above 40 even for lower-end players, and the vanilla world borer doesn't help with that.

**Comment by NoChanceSD** [comment]
Oh i see what you mean.

**Comment by TheExceed** [comment]
Was the worldborder integration added?

**Comment by NoChanceSD** [comment]
Yes, teleport is no longer blocked so this shouldn't be an issue anymore. I might re-add the teleport blocking later.
