### ISSUE TITLE
NPE PlayerCommandPreprocessEvent

### ISSUE THREAD

**Issue by Europia79** [NoChanceSD/PvPManager#41]
http://pastebin.com/snF6nL3w

A user reported this issue to me.

Caused by PlayerHandler.get()... I see another event handling the possibility of null while the PlayerCommandPreprocessEvent does not check for null.

The reason for null is because the Player is not contained within the players HashMap, nor are they contained within getServer().getPlayer()

I think it would be okay to always return the object... except limit object saving to only those that pass the getServer().getPlayer() check. This way, null is never returned.

**Comment by Europia79** [comment]
```
	private PvPlayer add(final Player player) {
		if (plugin.getServer().getPlayer(player.getUniqueId()) == null)
			return null;
		final PvPlayer pvPlayer = new PvPlayer(player, plugin);
		players.put(player.getUniqueId(), pvPlayer);
		pvPlayer.loadPvPState();
		return pvPlayer;
	}
```

This is the original code: If i'm reading it correctly, the purpose & intention of the first conditional-check is to prevent SAVING the PvPlayer object to the players HashMap ?

From what I've seen, get() and subsequently add() are being called from Events... So I think it would be safe to simply return the created object... in order to avoid returning a null (if possible).

The only question is if the object gets saved or not. See my edited code:

```
	public final PvPlayer get(final Player player) {
		final UUID uuid = player.getUniqueId();
		return players.containsKey(uuid) ? players.get(uuid) : add(player);
	}

	private PvPlayer add(final Player player) {
		final PvPlayer pvPlayer = new PvPlayer(player, plugin);
		pvPlayer.loadPvPState();
		return save(pvPlayer);
	}

	private PvPlayer save(final PvPlayer p) {
		if (plugin.getServer().getPlayer(p.getUUID()) != null) {
			players.put(p.getUUID(), p);
                }
		return p;
	}
```

I don't think this is the only solution tho. There are other possible solutions, like checking for null. What do you think ?

**Comment by NoChanceSD** [comment]
So what kind of player triggered that NPE? Some NPC?
And yes, the point of that check was to avoid saving a PvPlayer object from for example a NPC which could lead to memory leaks. Your solution seems fine though, will probably add it, thanks.

**Comment by NoChanceSD** [comment]
Merged PR.
