### ISSUE TITLE
/announce command?!?

### ISSUE THREAD

**Issue by MarvinKlar** [NoChanceSD/PvPManager#452]
**Describe the bug**
Users can use "/announce", but that command is not mentioned anywhere?

**To Reproduce**
1. Install PvPManager, start the server, run "/announce test"

**Expected behavior**
I expect this command not to be there.

**Plugin and Server version**
Any

**Screenshots**
![grafik](https://github.com/ChanceSD/PvPManager/assets/34421947/53f64cc9-d7b0-4d63-968f-748ca322bbda)

**Comment by ChanceSD** [comment]
That announce is not from PvPManager.

**Comment by MarvinKlar** [comment]
It is, when disabling the plugin, the command is no longer there

**Comment by MarvinKlar** [comment]
@ChanceSD

**Comment by ChanceSD** [comment]
It is not, there is no message saying "You have to use /announce <message>" here, and the command from here requires a permission https://github.com/ChanceSD/PvPManager/blob/master/pvpmanager/src/main/java/me/NoChance/PvPManager/Commands/Announce.java
Also do not spam.
