### ISSUE TITLE
Error with "/pm" command

### ISSUE THREAD

**Issue by PabloM98** [NoChanceSD/PvPManager#50]
I receive this error (http://pastebin.com/RHt4Ya3W) in the console every time that someone without permissions uses the command "/pm". In the server chat appears "An internal error occurred while attempting to perform this command".
I use Spigot 1.8.7 and PvPManager 3.0-SNAPSHOT-b118.

**Comment by EvilOlaf** [comment]
Maybe a problem with Essentials. Try latest from here
https://hub.spigotmc.org/jenkins/job/Spigot-Essentials/
or even better https://ci.drtshock.net/job/EssentialsX/

**Comment by PabloM98** [comment]
I use Spigot-Essentials #12

**Comment by NoChanceSD** [comment]
I have seen some issues where the /pm command goes from being assigned to PvPManager to being assigned to Essentials after a reload. That doesn't seem to be your problem here, just letting you know, will try to get that fixed.
