### ISSUE TITLE
Jail punishment is jailing people but not moving them.

### ISSUE THREAD

**Issue by FrozenBeard** [NoChanceSD/PvPManager#52]
we have 100% success rate at using the manual /jail username 5m cell1
But recently in the last few weeks (Since updating Spigot) There is an issue with PVPManager issuing punishment commands, They sometimes work, they sometimes don't.

We have our punishment for killing a player over and over set to jail them for 5 mins to cool down, Whats happening recently is the player is getting "Jailed" but its not teleporting them to the cell, so they are stuck as "Jailed" until they are killed, sometimes the player gets jailed after they have been killed.

**Comment by NoChanceSD** [comment]
It's because of the teleport blocking while in combat, will get fixed.

**Comment by FrozenBeard** [comment]
Superb! I'm glad you know the issue. Thanks man.
