### ISSUE TITLE
Issue with PvPLog message

### ISSUE THREAD

**Issue by PabloM98** [NoChanceSD/PvPManager#54]
Please put the PvP Log message as it was before again. The bukkit command /say don't support color codes and appears with the tag [Server] before the message. Same with PvP Toggle messages.

**Comment by EvilOlaf** [comment]
Replace with a `tellraw` command.
But I am not sure if the `config.yml` is fully compatible with the json formatting.

For easier generation of a nice json msg use http://minecraftjson.com/

**Comment by PabloM98** [comment]
/tellraw is just to send a private message to a user, not a broadcast.

**Comment by NoChanceSD** [comment]
Use '/tellraw @a' to send the message to all online players.
However, i might create a simple command like /announce or similar to broadcast the message in a cleaner way.

**Comment by PabloM98** [comment]
Why not leave messages on the messages.properties? It was much easier.

**Comment by NoChanceSD** [comment]
Because some people don't use the broadcast, also it doesn't make sense to keep the broadcast when executing custom commands allows for that and much more.

**Comment by PabloM98** [comment]
I have tried to remove all commands from the option and the default set command still executing... 
I will stay on PvPManager 3.0-SNAPSHOT-b118 for the moment.
