### ISSUE TITLE
players can kill if pvp is off

### ISSUE THREAD

**Issue by voigtman** [NoChanceSD/PvPManager#55]
Players can be tagged and even battle with it off.

**Comment by NoChanceSD** [comment]
Using latest version?

**Comment by voigtman** [comment]
At the time of the post, 3.0 (3.0-SNAPSHOT-b102) was the latest and yes at that time I was.  
I have not upgraded to the latest latest version. (PvPManager v3.0-SNAPSHOT-b143) I will try this.

**Comment by NoChanceSD** [comment]
The latest was released on Sunday so it was almost one week ago. Anyway, let me know if it still happens.
