### ISSUE TITLE
PvPManager overrides  passthrough and entry region flags

### ISSUE THREAD

**Issue by Shananium** [NoChanceSD/PvPManager#56]
Hi,

While player is tagged, they can enter areas what has passthrough: DENY and entry: DENY flags - where they normally can't enter. I was unable to solve this with config file.

- Shana

**Comment by NoChanceSD** [comment]
Are you using the latest version?

**Comment by Shananium** [comment]
Not using latest version, updating it to latest build tomorrow and I'll check if the issue is still on.

**Comment by Shananium** [comment]
Hi,

After updating to latest build the issue was solved. Thank you NCSD :+1: 

- Shana
