### ISSUE TITLE
Punishment on kick

### ISSUE THREAD

**Issue by TheExceed** [NoChanceSD/PvPManager#57]
There is no feature to not kill on kick.
I have an anti-hack plugin that kicks for use of hacks but it also considers that as a combat-log,
can this be added?

**Comment by EvilOlaf** [comment]
Set `  Kill on Logout: true` to false?

**Comment by TheExceed** [comment]
Oh sorry didn't see the response, no I want them to be kill for combat logging, but I have multiple other plugins that kick for various reasons and kicking a player should not kill them.

**Comment by EvilOlaf** [comment]
So you're issue should be solved with the setting mentioned above?

**Comment by TheExceed** [comment]
False. if I change the setting above people can logout during combat and nothing would happen to them.
