### ISSUE TITLE
Locale setting does not save

### ISSUE THREAD

**Issue by EvilOlaf** [NoChanceSD/PvPManager#60]
When I change the `Locale:` to `de`and do a reload of the config it switches always back to `en`.
However it use the German translation anyways, so it's a minor issue.

Build 144

**Comment by NoChanceSD** [comment]
This doesn't happen to me, might have got fixed by some recent changes, let me know if not.

**Comment by EvilOlaf** [comment]
Did no further debug since it kept using the German lang file after a restart...a `pm reload` did not catch it if I remember correctly.

Anyway it works for me.
