### ISSUE TITLE
Command conflict on pm with Essentials

### ISSUE THREAD

**Issue by EvilOlaf** [NoChanceSD/PvPManager#61]
PvPmanager and Essentials both using the `pm` command.
After a pm reload the pm command is no longer assigned to PvPmanager,  it felt back to Essentials so it is no longer usable.

Build 144

**Comment by Blackyvk** [comment]
you can use /pvpmanager

**Comment by EvilOlaf** [comment]
I know that. It is a minor issue though.

**Comment by NoChanceSD** [comment]
There is also /pvpm
I will see what i can do though.

**Comment by EvilOlaf** [comment]
I think no-one will complain if you remove the pm alias. Pvpm should work as well.

**Comment by NoChanceSD** [comment]
I'm going to fix it anyway, i also like to use /pm reload while debugging and have noticed this issue quite some times, it's annoying.
