### ISSUE TITLE
Sometimes a player not getting tagged properly

### ISSUE THREAD

**Issue by EvilOlaf** [NoChanceSD/PvPManager#68]
Currently I have a player that does not have his name tagged either with the pvp or not-pvp color.
He also does not get tagged properly when in fight.

Not sure if that happens while he was in combat and I reloaded the plugins configuration.

The player has no special permission nodes as others.

Build 144

Edit: Yep, happens sometimes when reloading the plugin and players are in combat.

**Comment by NoChanceSD** [comment]
There are some issues with reloading since i made the change to avoid losing /pm to Essentials, will see what i can do.

**Comment by EvilOlaf** [comment]
Actually the issue persists.
A team mate told me that when a player renames himself he won't be tagged anymore properly. Even after reload or changing the pvp status the tag is not set. Hard to believe that a rename should cause this...weird.

**Comment by NoChanceSD** [comment]
Rename as in Mojang rename or /nick command?
And yes, you have some info with /pvpinfo and there are some debug commands like "/pm debug tag" which require permission "pvpmanager.debug"

**Comment by EvilOlaf** [comment]
Mojang rename.
Will test when the player is online again.

**Comment by EvilOlaf** [comment]
Output for the concerning player:
```
- Name: SmauMC
- PvP Status: true
- Tagged: false
- Newbie: false
- World: world
- Override: false
```

`pm debug tag` did not perform any actions or changes tags.

**Comment by NoChanceSD** [comment]
Did the player execute pm debug tag ? It should tag himself, if it doesn't he might have the permission to bypass tagging or be an OP which i doubt. I'm not seeing other possibilities right now.

**Comment by EvilOlaf** [comment]
Ah okey, didn't realize that the player should exeute this by himself.

He executed the command and got tagged. The color code has been applied. After the tag hes expired his name is as previous not tagged anymore at all.

**Comment by NoChanceSD** [comment]
Does the player he attacks or gets attacked by become tagged? Is the server in online mode?
Any NPC with that player's name?
I don't think the cause can be the name change, try restarting the server if you didn't.

**Comment by EvilOlaf** [comment]
1. Did not test yet.
2. Yes, online mode
3. We do not have NPCs.
4. For this I'll wait a few hours as the daily restart will executed anyways. Let's wait till then and see if persists.

**Comment by NoChanceSD** [comment]
Any news on this?

**Comment by EvilOlaf** [comment]
Sorry, forget about. 

The specific user is now tagged properly but no idea if the restart fixed this or anything else...

**Comment by NoChanceSD** [comment]
Weird, i use UUID internally so there shouldn't be issues... anyway, i'm going to close the ticket as i don't see how i could prevent it.

**Comment by EvilOlaf** [comment]
Aight, I'll catch up when it happens again.

**Comment by EvilOlaf** [comment]
Just did a `pm reload` for adding some commands to the whitelist and now I have two players without colored name tags. Both of them have pvp-status true.

Tried to change their name coloring by hitting them so both me and one of them should get tagged but their name stays white.

Noted their names and I'll update if this has been fixed after the daily restart in a couple of hours or even earlier when they reconnect.

3.0-b154

**Comment by EvilOlaf** [comment]
Seems like they are now probably name-tagged. So restart fixes this.
