### ISSUE TITLE
Using -pvpmanager.nocombat

### ISSUE THREAD

**Issue by idkw** [NoChanceSD/PvPManager#69]
When using the negate node "-pvpmanager.nocombat" ops players still get pvp disabled by default and always have to type /pvp after they login.

**Comment by NoChanceSD** [comment]
Well, considering how long it took me to answer, you probably don't care anymore but the permission you have to negate is pvpmanager.nopvp. Sorry for the delay.

**Comment by idkw** [comment]
Actually I'm still using PvpManager and still got the issue. Thank you for answering.
