### ISSUE TITLE
WorldGuard bug

### ISSUE THREAD

**Issue by TheExceed** [NoChanceSD/PvPManager#71]
If you are tagged for combat before entering a region, you can still combat players in the region.

**Comment by EvilOlaf** [comment]
This is not a bug. That's a toggleable feature.
Set `Ignore Zones For Tagged: true` to `false` to change the behaviour.

**Comment by TheExceed** [comment]
Hm, I changed that awhile ago but it didn't work but seems to work now? Idk  soz
