### ISSUE TITLE
Preventing tagged players from exiting worldguard regions

### ISSUE THREAD

**Issue by GuloLuscus66** [NoChanceSD/PvPManager#76]
Hi. I have a worldguard protected pvp-arena with mobspawners for xp-harvesting where players get a pvp-kit on entry, after getting their inventory emptied, and their inventory is emptied again on exit and they are the tp'ed out of the arena. I use pvpmanager to prevent pvp-logging, but players sometimes go to the exit and gets teleported out of the arena even when they are tagged. 

Is it possible to prevent tagged players from exiting regions? 

Or is the solution to skip the tp out and have exit by death only (allow the /suicide command)? That would mean I cant have a combined pvp-arena/xp-harvest-arena.

**Comment by NoChanceSD** [comment]
How are they teleported out? Clicking on signs?

**Comment by GuloLuscus66** [comment]
By stepping on pressure plate that triggers command blocks that removes inventory and teleports

**Comment by NoChanceSD** [comment]
Can you check if latest build fixes this?

**Comment by NoChanceSD** [comment]
Closing since i didn't get a reply.
