### ISSUE TITLE
Tamed wolves do not defend their owner while the owner is combat tagged

### ISSUE THREAD

**Issue by deletethisgit** [NoChanceSD/PvPManager#77]
If the owner of a wolf is attacked by another player, the wolf will not defend its owner as expected. When the owner's combat tag expires, the wolf will then attack. But it will never attack while the owner is combat tagged. If the owner is killed by another player, removing the owner's combat tag, the wolves will attack whoever killed their owner.

This bug isn't present for operators. If the attacker of a tamed wolf owner is an operator, the wolves will attack him as usual.

**Comment by NoChanceSD** [comment]
Interesting, thanks for the report.

**Comment by NoChanceSD** [comment]
It seems tamed animals won't attack players in the same team as their owner.
I'm not sure if this is minecraft behavior or spigot behavior.
