### ISSUE TITLE
Per world features.

### ISSUE THREAD

**Issue by MithrandirCraft** [NoChanceSD/PvPManager#80]
I have some pvp rooms on another world, where players tend to save themselves behind the line (it's sort of a hit & run situation)

This world is excluded from pvpmanager's features, because I don't want players to die and lose their items there when disconecting.

Still, I would like the safezones to stop being safe if a pvp has already started. That would be perfect, therefore, is there anyway I can get this specific anti safezone during pvp feature to work in this world? :)

**Comment by NoChanceSD** [comment]
You could enable minecraft's gamerule to keep inventory on that world but i don't think you want that.Excluding that i don't think there is really another way. 

Even if i added the option of disabling each feature per world, you would then disable the "Tagged in Combat" section to disable player drops, however the anti safezones feature needs to check if a player is in combat so it would have to be disabled as well.

I'm not sure if i explained that properly but what i mean is that it is possible but i can't think of a "good for all servers" solution. If you have suggestions let me know.

**Comment by MithrandirCraft** [comment]
No problem. :)

In fact, the gamerule idea does seem interesting, but I don't understand how your plugin works internally.

Lets say i activate your plugin on that world. Would it be enough with disabling Vanilla item drops in order to prevent drops when a player logs out during a PVP?

In any case, when I eventually activate NPC's (because right now they are broken) those NPC's would still show up, and it would look awquard, but following the same logic, once the npc's are killed, no items would be spilled. Is that so?

**Comment by NoChanceSD** [comment]
Yes, the gamerule should work just fine for a player.
However, for NPC's i'm not sure but they should follow the same behavior.

**Comment by NoChanceSD** [comment]
Closing as it's not an issue anymore (i think?)
Also, NPCs should now work fine as you know.
