### ISSUE TITLE
Some more issues

### ISSUE THREAD

**Issue by EvilOlaf** [NoChanceSD/PvPManager#83]
I set locale to de. After reloading it became all phrases are English again, but in the config it is still set to de. Also the messages_de file disappeared and the default one was created. This is not a new issue though. I solved this earlier by replacing all phrases at the default messages file with the German ones.

It also seems like that PM gets his config from an internal invisible config file as for example I defined other color codes for nametags but the are colored like default (blue and green).

Build 174

**Comment by NoChanceSD** [comment]
Let me know if latest build fixes this.

**Comment by EvilOlaf** [comment]
Looks good. I'll do some further testing.
