### ISSUE TITLE
Users can equip armour while in combat!!

### ISSUE THREAD

**Issue by Jaackk** [NoChanceSD/PvPManager#84]
Users can re-equip armour while in combat to re-activate effects such as life bonus / health boost (example) for infinite health. If there was a way you could disable them from taking on and off armour while in combat that would be amazing!!

Thank you for your time,

Best regards,
Jack.

**Comment by NoChanceSD** [comment]
I don't know if there would be any benefit in blocking this. 
Afaik most servers don't use these type of effects, you should ask the plugin developer to block them.
