### ISSUE TITLE
Nametag Issues

### ISSUE THREAD

**Issue by MeMyselfMC** [NoChanceSD/PvPManager#85]
Just updated to this build: http://ci.md-5.net/job/PvPManager/174/

When players tag someone else in combat, their nametag changes to "none<Player Name Here>". For some reason setting the option to 'none' in the config doesn't disable the feature.

**Comment by MeMyselfMC** [comment]
It also would be nice to see the silent combat option back.

**Comment by NoChanceSD** [comment]
Let me know if latest build fixes this.
Silent option won't be back but maybe an alternative will be added such as deleting a message from properties file.
