### ISSUE TITLE
Console error issue

### ISSUE THREAD

**Issue by LeDadSnatcher** [NoChanceSD/PvPManager#87]
For the past day, some players have not been able to take damage whilst still being able to hit people, sometimes this was also reversed. I first thought that this was to do with pvpmanager and had tried toggling it on and off but it still had no change. I found an error in my logs which looks like it would be the issue to the pvp problems but idk atm.

Here is the error: http://pastebin.com/XixMprJA

Using latest version on spigot 1.8.7

**Comment by LeDadSnatcher** [comment]
So regarding the issue, when a player has newly joined they cannot take damage but if I do a restart, they can. Does this relate to the issue I have been having? This is pretty urgent.

**Comment by LeDadSnatcher** [comment]
Seems to be fixing itself after a while now without newbie protection, weird but I still think that the error provided has something to do with it. Sorry for all the replies so far, just trying to keep you updated on what I know.

**Comment by NoChanceSD** [comment]
Check if latest update fixes this issue please.

**Comment by LeDadSnatcher** [comment]
Still getting this (or a similar issue)

Error: http://pastebin.com/692LaVvh

**Comment by NoChanceSD** [comment]
Hmmm, can you list me all plugins you have using scoreboards?

**Comment by LeDadSnatcher** [comment]
I use featherboard.

**Comment by NoChanceSD** [comment]
Just featherboard? Well, i will try to test and reproduce the bug then.
