### ISSUE TITLE
Players not being combat tagged.

### ISSUE THREAD

**Issue by LeDadSnatcher** [NoChanceSD/PvPManager#90]
Having an issue where players are not being tagged when hit.

Error:
http://pastebin.com/TGmzmE8f

Using the latest version of PvPManager and Featherboard.

**Comment by NoChanceSD** [comment]
Well, i don't own the plugin Featherboard so maybe you should ask the dev to not unregister other plugins teams.

**Comment by LeDadSnatcher** [comment]
Just got a reply from the developer of Featherboard after submitting the error. His response was "
The error is in PVPManager, they use a scoreboard. Error would appear on any scoreboard plugin used in combination with that plugin"

**Comment by NoChanceSD** [comment]
I use PvPManager with several plugins using scoreboards without issues, mcmmo, coloredtags, jobs are some examples and they all work fine. So yea, he's doing it wrong.

**Comment by EvilOlaf** [comment]
Please forgive me my interfer but I think it would make sense to directly in touch with each other rather than using @LeDadSnatcher as some kind da intermediary ;). There is no need for conjecture who is wrong. Just give it a professional talk :).

**Comment by NoChanceSD** [comment]
You are right, i'm here though. This is a public issue, that author is free to come in, i'm open to suggestions.

**Comment by NoChanceSD** [comment]
Not sure if there are still any issues with this, i can reopen if there are.
