### ISSUE TITLE
Request: Newbie Protection Command Blacklist

### ISSUE THREAD

**Issue by FrozenBeard** [NoChanceSD/PvPManager#93]
Newbies have the option to be PVP immune for x amount of time, having the option to blacklist commands during this PVP free time would be fantastic. For instance: I have a 2 hour immunity for brand new players using PVPManager, issue being is that they can /siege other players claims, but the defendant cannot kill them in retaliation to win the siege.
I could remove the option to siege from all of this rank, but then that removes gameplay, it needs to be timed with the PVP. Therefor I request having a blacklist of commands during this Protection period, this could be used in a multitude of ways.

**Comment by NoChanceSD** [comment]
Sorry, i don't think i will be adding this but will leave it open in case i change my mind.
