### ISSUE TITLE
PvP on/off broadcast and message itself cannot be changed now?

### ISSUE THREAD

**Issue by Cassolotl** [NoChanceSD/PvPManager#99]
You know that "so-and-so is scared and has turned PvP off!" message? I updated PvPManager and I can't turn that off now. There's nothing in the config about it any more, but there is a setting in a file called something like "old config" that was created during the update to the newer version.

There's also nothing in the messages file to let me edit the message.

Please bring back the option to not broadcast people turning PvP on and off, and to edit the message broadcast! Thank you. :)

**Comment by NoChanceSD** [comment]
Just delete the announce command in the config

**Comment by Cassolotl** [comment]
@NoChanceSD There is no announce command in the config. At least, ctrl+F "announce" gives 0 results. Is it called something else?

**Comment by EvilOlaf** [comment]
So you have no broadcast or similar in this section: 
```
PvP Toggle:
  Cooldown: 15
  NameTags:
    Enabled: false
    Prefix On: '&1'
    Prefix Off: '&2'
  Commands PvP On: []
  Commands PvP Off: []
  Force On Change World: false
```
?

**Comment by Cassolotl** [comment]
Here's what I've got:

![screen shot 2016-03-04 at 17 06 45](https://cloud.githubusercontent.com/assets/6607512/13534133/902e7838-e22b-11e5-86ab-ffdb2df3a26b.png)

None of that says anything about announcing or broadcasting, right? None of it seems to be talking about a message broadcast when you turn your PvP on or off.

Or do I need to delete part of this section? If so, it's not clear which part you mean from "the announce command" - none of this is obviously an announce command to me.

**Comment by NoChanceSD** [comment]
What is your PvPManager version btw?

**Comment by Cassolotl** [comment]
@NoChanceSD There's no version number on the .jar file - how do I find out my version number?

**Comment by NoChanceSD** [comment]
'/ver pvpmanager' should work

**Comment by EvilOlaf** [comment]
Use `/version pvpmanager`. If you are using a dev build the build number will be show up at the end.

**Comment by Cassolotl** [comment]
@NoChanceSD Here's what my console said:

> [18:15:31] [Server thread/INFO]: [0;32;1mPvPManager[0;37;1m version [0;32;1m3.0-SNAPSHOT-b190[m

**Comment by EvilOlaf** [comment]
Grab the latest dev build: http://ci.md-5.net/job/PvPManager/changes
Seems like build 193 fixed this.

**Comment by Cassolotl** [comment]
@EvilOlaf I don't know how to install this. But I can wait for a stable build update thing - any idea how long it'll be?

**Comment by NoChanceSD** [comment]
Click here: http://ci.md-5.net/job/PvPManager/lastSuccessfulBuild/artifact/target/PvPManager.jar

**Comment by Cassolotl** [comment]
@NoChanceSD Thank you! I have done this. :) I can't see any obvious broadcast/announce type settings in config, and I am not sure what to change in the messages file - what am I looking for?

**Comment by NoChanceSD** [comment]
This should be solved so i'm closing.
